### PR TITLE
Fix for the XP-Pen Deco 01

### PR DESCRIPTION
**Pull request by Itsyuka**
Correct Product ID, init and report length

Should close https://github.com/hawku/TabletDriver/issues/258 and https://github.com/hawku/TabletDriver/issues/246

### CODE REVIEW

**Comment by hawku** [comment]
@Itsyuka That change will remove the support for original Deco 01 and will only support the latest version.

XP-Pen likes to make multiple different versions of the same tablet. There are at least two different versions of Deco 01.
They have done this with other tablet models too and it is very hard to keep track of these changes.

Could you add the new Deco 01 tablet as a new tablet to the config and test it out:
```
#
# XP-Pen Deco 01 v2
#
Tablet 0x28BD 0x0902 0xFF0A 0x0001
Name "XP-Pen Deco 01 v2"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 25400
MaxY 15875
MaxPressure 8191
Width 254.0
Height 158.75
InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00
```

**Comment by Itsyuka** [comment]
Alright I reverted the previous change and created a new entry instead, and yes it's confirmed working.

**Comment by Itsyuka** [comment]
Also I want to make a note, there is hardware smoothing and even at this size of a tablet, I don't recommend switching from the official drivers. This is only to support the tablet for people to try it out.

**Comment by hawku** [comment]
@Itsyuka Thanks!

XP-Pen drivers are better for Deco 01, because those drivers will provide better support for drawing applications.

**Pull request merged**
