### PR TITLE
more tablets

### PR DESCRIPTION
**Pull request by preperation**
wacom intuos m ctl-6100

I'd love it if the tablet was added.

### CODE REVIEW

**Comment by Pawder** [comment]
Id love to see the H610 pro v2 :-) 

Even though it might be like the H610 drivers as well, make a awesome solution :)

**Comment by ItzSky** [comment]
Can you do one for the Gaomon M106k. It's not usually a tablet that a lot of others use for Osu but I'd appreciate it if it was a thing

**Comment by xxunit2005xx** [comment]
Can you do one for the veikk s640. It would be much appreciated.

**Comment by Valihack** [comment]
would be nice having the deco 01 support

**Comment by Veykiou** [comment]
Can you make the XP-Pen 16 suport ?

**Comment by riley-badour** [comment]
i would love to help this project by  get your tablet supported but i need people to contact me on discord so i get get information off your tablet like the pid and vid and usage page and usage numbers
i would also like to talk to hawku usbdevice part of the program and how it functions as i don't quite understand how it works it's knowledge will be need for veikk support for sure
discord server is https://discord.gg/jXXncv contact me on there for helping you get you tablet up on running il gladly be of service.

**Comment by Saxarokkkk** [comment]
Can you do it for tablet xp pen star 03 and star 03s? I will grateful you.=)

**Comment by nieacry** [comment]
Huion HS610 support is extremely needed = (

**Comment by zMici** [comment]
I'd love to have Huion HS64 as a supported tablet.

**Comment by HaritoBG** [comment]
Would you mind to add VEIKK A15 please, I will be very grateful!

**Pull request closed without merging**
